const fs=require('fs');
const f=process.argv[2];
const p=JSON.parse(fs.readFileSync(f,'utf8'));
const pak=fs.readFileSync('tools/pak_classes.txt','utf8').split(/\r?\n/).map(l=>l.trim().split(/\s+/)[1]).filter(n=>n&&/Class158/.test(n)&&!/Base$/.test(n));
p.rail_class_information=[...new Set(pak)].map(c=>({class_name:c+'_C'}));
const by=n=>p.controls.find(c=>c.name===n);
const tog=(name,desc,node,on,off)=>({name,description:desc,assignment:{type:'toggle',threshold:0.9,action_activate:{controls:node,value:on,hold:false,enable_api_fallback:true},action_deactivate:{controls:node,value:off,hold:false,enable_api_fallback:true}}});
const rel=(node,v)=>({type:'momentary',threshold:0.9,action_activate:{controls:node,value:v,relative:true,hold:false,enable_api_fallback:true}});
const rv=by('SpeedbrakeLever'); rv.description='Reverser (Off / Reverse / Neutral / Forward)'; rv.assignments[0].input_value.max=0.75; rv.assignments[0].input_value.steps=[0,0.25,0.5,0.75];
by('LeftThrottle').description='Train brake (Release / Step 1 / Step 2 / Full service / Emergency)';
by('RightThrottle').description='Throttle (Off / 1 / 2 / 3 / 4 / 5 / 6 / 7)';
by('ParkingBrake').description='Master key on / off';
by('GearLever').assignment={type:'momentary',threshold:0.9,action_activate:{keys:'Q'}};
by('RotaryCrank').description='Wipers one notch towards Slow (Fast > Park > Slow)'; delete by('RotaryCrank').assignment; by('RotaryCrank').assignments=[rel('WiperControl_L',0.5),rel('WiperControl_R',0.5)];
by('RotaryIgnStart').description='Wipers one notch towards Fast (Slow > Park > Fast)'; delete by('RotaryIgnStart').assignment; by('RotaryIgnStart').assignments=[rel('WiperControl_L',-0.5),rel('WiperControl_R',-0.5)];
const hl=[['Off',0],['Day headlight',0.875],['Marker only',0.375],['Night headlight',0.125],['Tail only',0.625]];
hl.forEach(([n,v],i)=>{const c=by('AutoBrake'+i);c.description='Headlights | '+n;c.assignment.action_activate.value=v;});
const ins=(after,item)=>{const i=p.controls.findIndex(c=>c.name===after);p.controls.splice(i+1,0,item);};
ins('RoundAuxButton',tog('LeftAuxButton','AWS isolation (lit = Isolated / unlit = Normal)','AWS_Isolation',1,0));
ins('LeftAuxButton',tog('RightAuxButton','Vigilance isolation (lit = Isolated / unlit = Normal)','Vigilance_Isolation',1,0));
fs.writeFileSync(f,JSON.stringify(p,null,2)+'\n');
console.log(p.rail_class_information.map(c=>c.class_name).join(' '));
console.log(p.controls.map(c=>c.name+' :: '+c.description).join('\n'));
