const fs=require('fs');
const f=process.argv[2];
const p=JSON.parse(fs.readFileSync(f,'utf8'));
const pak=fs.readFileSync('tools/pak_classes.txt','utf8').split(/\r?\n/).map(l=>l.trim().split(/\s+/)[1]).filter(n=>n&&/Class323/.test(n)&&!/Base$/.test(n));
p.rail_class_information=[...new Set(pak)].map(c=>({class_name:c+'_C'}));
const by=n=>p.controls.find(c=>c.name===n);
const mom=(name,desc,node,on,off,hold=true)=>({name,description:desc,assignment:{type:'momentary',threshold:0.9,action_activate:{controls:node,value:on,hold},action_deactivate:{controls:node,value:off,hold:false}}});
const tog=(name,desc,node,on,off)=>({name,description:desc,assignment:{type:'toggle',threshold:0.9,action_activate:{controls:node,value:on,hold:false,enable_api_fallback:true},action_deactivate:{controls:node,value:off,hold:false,enable_api_fallback:true}}});
const set=(node,v)=>({type:'momentary',threshold:0.9,action_activate:{controls:node,value:v,hold:false}});
const rel=(node,v)=>({type:'momentary',threshold:0.9,action_activate:{controls:node,value:v,relative:true,hold:false,enable_api_fallback:true}});
const ins=(after,item)=>{const i=p.controls.findIndex(c=>c.name===after);p.controls.splice(i+1,0,item);};
p.controls=p.controls.filter(c=>!['LeftAuxButton','RightAuxButton'].includes(c.name));
ins('SpeedbrakeLever',{name:'LeftThrottle',description:'Power / brake handle (B3 / B2 / B1 / Off / P1 / P2 / P3 / P4; Emergency at -1 is left out on purpose, as in the old 323 profile)',assignments:[{type:'direct_control',controls:'PowerBrakeHandle',input_value:{min:-0.6,max:1,steps:[-0.6,-0.4,-0.2,0,0.25,0.5,0.75,1],invert:true}}]});
by('ParkingBrake').description='Master key in / out';
by('GearLever').description='AWS reset'; by('GearLever').assignment={type:'momentary',threshold:0.9,action_activate:{keys:'Q'}};
ins('LeftThrottleButton',mom('RightThrottleButton','Pantograph raise','PantographRaise',1,0));
ins('RoundAuxButton',tog('LeftAuxButton','AWS isolation (lit = Isolated / unlit = Normal)','AWS_Isolation',1,0));
ins('LeftAuxButton',tog('RightAuxButton','Vigilance isolation (lit = Isolated / unlit = Normal)','Vigilance_Isolation',1,0));
by('RotaryCrank').description='Wipers one notch slower (Fast > Slow > Int 2 > Int 1 > Off)'; delete by('RotaryCrank').assignment; by('RotaryCrank').assignments=[rel('WiperControl',-0.25)];
by('RotaryIgnStart').description='Wipers one notch faster (Off > Int 1 > Int 2 > Slow > Fast)'; delete by('RotaryIgnStart').assignment; by('RotaryIgnStart').assignments=[rel('WiperControl',0.25)];
const HL='HeadlightsMarkerLights',TL='TailLights';
const dial=[['Off',0.5,0],['Day head',0.75,0],['Marker lights',0,0],['Night head',0.25,0],['Tail lights',0.5,1]];
dial.forEach(([n,h,t],i)=>{const c=by('AutoBrake'+i);c.description='Headlights | '+n;delete c.assignment;c.assignments=[set(HL,h),set(TL,t)];});
fs.writeFileSync(f,JSON.stringify(p,null,2)+'\n');
console.log(p.rail_class_information.map(c=>c.class_name).join(' '));
console.log(p.controls.map(c=>c.name+' :: '+c.description.slice(0,70)).join('\n'));
